---
- hosts: all
  become: true
  tasks:
    - name: Update repository index
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    
    - name: Update repository index
      yum:
        update_cache: yes
      when: ansible_distribution == "CentOS"


- hosts: Controller
  become: true
  vars:
    CINDER_DBPASS: "your_cinder_db_password"
    CINDER_PASS: "your_cinder_user_password"
    RABBIT_PASS: "your_rabbitmq_password"
  roles:
    - Controller

- hosts: Compute
  become: true
  roles:
    - Compute
